/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalendarDays {
    'changeSelectedDate': Function;
    'month': any;
    'options': any;
    'selectedDate': any;
    'year': any;
  }
  interface CalendarDisplay {
    'changeSelectedDate': Function;
    'options': any;
    'selectedDate': any;
    'shouldCalendarOpen': Boolean;
  }
  interface CalendarMonth {
    'goToNextMonth': Function;
    'goToPrevMonth': Function;
    'month': any;
    'year': any;
  }
  interface CalendarWeek {}
  interface DatePicker {
    'currentdate': any;
    'getValue': () => Promise<string>;
    'options': any;
    'setValue': (date: any) => Promise<void>;
  }
}

declare global {


  interface HTMLCalendarDaysElement extends Components.CalendarDays, HTMLStencilElement {}
  var HTMLCalendarDaysElement: {
    prototype: HTMLCalendarDaysElement;
    new (): HTMLCalendarDaysElement;
  };

  interface HTMLCalendarDisplayElement extends Components.CalendarDisplay, HTMLStencilElement {}
  var HTMLCalendarDisplayElement: {
    prototype: HTMLCalendarDisplayElement;
    new (): HTMLCalendarDisplayElement;
  };

  interface HTMLCalendarMonthElement extends Components.CalendarMonth, HTMLStencilElement {}
  var HTMLCalendarMonthElement: {
    prototype: HTMLCalendarMonthElement;
    new (): HTMLCalendarMonthElement;
  };

  interface HTMLCalendarWeekElement extends Components.CalendarWeek, HTMLStencilElement {}
  var HTMLCalendarWeekElement: {
    prototype: HTMLCalendarWeekElement;
    new (): HTMLCalendarWeekElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };
  interface HTMLElementTagNameMap {
    'calendar-days': HTMLCalendarDaysElement;
    'calendar-display': HTMLCalendarDisplayElement;
    'calendar-month': HTMLCalendarMonthElement;
    'calendar-week': HTMLCalendarWeekElement;
    'date-picker': HTMLDatePickerElement;
  }
}

declare namespace LocalJSX {
  interface CalendarDays extends JSXBase.HTMLAttributes<HTMLCalendarDaysElement> {
    'changeSelectedDate'?: Function;
    'month'?: any;
    'options'?: any;
    'selectedDate'?: any;
    'year'?: any;
  }
  interface CalendarDisplay extends JSXBase.HTMLAttributes<HTMLCalendarDisplayElement> {
    'changeSelectedDate'?: Function;
    'options'?: any;
    'selectedDate'?: any;
    'shouldCalendarOpen'?: Boolean;
  }
  interface CalendarMonth extends JSXBase.HTMLAttributes<HTMLCalendarMonthElement> {
    'goToNextMonth'?: Function;
    'goToPrevMonth'?: Function;
    'month'?: any;
    'year'?: any;
  }
  interface CalendarWeek extends JSXBase.HTMLAttributes<HTMLCalendarWeekElement> {}
  interface DatePicker extends JSXBase.HTMLAttributes<HTMLDatePickerElement> {
    'currentdate'?: any;
    'options'?: any;
  }

  interface IntrinsicElements {
    'calendar-days': CalendarDays;
    'calendar-display': CalendarDisplay;
    'calendar-month': CalendarMonth;
    'calendar-week': CalendarWeek;
    'date-picker': DatePicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


